import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/app/components/SessionWrapper";
import HeaderLayout from "@/app/components/HeaderLayouts";

const inter = Inter({ subsets: ["latin"], weight: ["400", "500", "700"] });


export const metadata: Metadata = {
  title: "PRESSOC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={inter.className}
      >
        <SessionWrapper>
          <HeaderLayout />
          {children}
        </SessionWrapper>
      </body>
    </html>
  );
}
